import type { SupabaseClient } from '@supabase/supabase-js';
import { getAdminClient } from './auth';

export type SeedWorkOptions = {
  title?: string;
  genre?: string;
  tags?: string[];
};

export type SeedEpisodeOptions = {
  episodeNumber?: number;
  title?: string;
  content?: string;
};

export type MockSixAxisScores = {
  hook?: number;
  character?: number;
  world?: number;
  tension?: number;
  emotion?: number;
  originality?: number;
};

const DEFAULT_E2E_TAG = 'e2e';
// MIN_ANALYSIS_CHARS in src/lib/manuscriptEligibility.ts is 500 — keep seed content above the floor.
const DEFAULT_EPISODE_CONTENT = '가나다'.repeat(200); // 600자

const DEFAULT_MOCK_RESULT = (scores: MockSixAxisScores = {}): Record<string, unknown> => {
  // Schema mirrors what AnalyzePanel.AnalysisResultDetailBody renders:
  //   - dimensions: { [snakeKey]: { score, comment } }  → formatDimensionLabel maps key → 한글
  //   - overall_score, improvement_points
  // Keys here resolve via src/lib/analysis/dimensionLabel.ts:
  //   hook_strength → "첫 훅·몰입", character_appeal → "인물 매력", worldbuilding → "세계관",
  //   tension → "긴장감", romance_potential → "로맨스·감정선", originality → "독창성"
  const dimensions = {
    hook_strength: { score: scores.hook ?? 80, comment: 'E2E mock comment' },
    character_appeal: { score: scores.character ?? 78, comment: 'E2E mock comment' },
    worldbuilding: { score: scores.world ?? 76, comment: 'E2E mock comment' },
    tension: { score: scores.tension ?? 82, comment: 'E2E mock comment' },
    romance_potential: { score: scores.emotion ?? 79, comment: 'E2E mock comment' },
    originality: { score: scores.originality ?? 75, comment: 'E2E mock comment' },
  };
  const arr = Object.values(dimensions).map((d) => d.score);
  const overall = Math.round(arr.reduce((a, b) => a + b, 0) / arr.length);
  return {
    overall_score: overall,
    dimensions,
    improvement_points: ['E2E mock improvement point'],
    summary: 'E2E mock — not generated by LLM',
    e2e_seed: true,
  };
};

async function resolvePublicUserIdByAuthId(
  client: SupabaseClient,
  authUserId: string,
): Promise<number> {
  const { data, error } = await client
    .from('users')
    .select('id')
    .eq('auth_id', authUserId)
    .maybeSingle();
  if (error) throw error;
  if (!data) throw new Error(`No public.users row found for auth_id=${authUserId}`);
  return Number(data.id);
}

/**
 * Idempotent — returns existing 'e2e'-tagged work for the given user if any, else inserts.
 * Caller passes auth.users.id (UUID); we resolve to public.users.id internally.
 */
export async function seedEmptyWork(
  authUserId: string,
  opts: SeedWorkOptions = {},
  client: SupabaseClient = getAdminClient(),
): Promise<number> {
  const userId = await resolvePublicUserIdByAuthId(client, authUserId);
  const tags = opts.tags ?? [DEFAULT_E2E_TAG];

  const { data: existing, error: lookupErr } = await client
    .from('works')
    .select('id')
    .eq('author_id', userId)
    .contains('tags', [DEFAULT_E2E_TAG])
    .is('deleted_at', null)
    .order('id', { ascending: true })
    .limit(1);
  if (lookupErr) throw new Error(`seedEmptyWork lookup failed: ${lookupErr.message}`);
  if (existing && existing.length > 0) return Number(existing[0].id);

  const { data: inserted, error: insErr } = await client
    .from('works')
    .insert({
      title: opts.title ?? 'E2E 테스트 작품',
      genre: opts.genre ?? '판타지',
      author_id: userId,
      tags,
    })
    .select('id')
    .single();
  if (insErr) throw new Error(`seedEmptyWork insert failed: ${insErr.message}`);
  return Number(inserted.id);
}

/**
 * Upsert by (work_id, episode_number) — UNIQUE constraint enforces idempotency.
 */
export async function seedEpisode(
  workId: number,
  opts: SeedEpisodeOptions = {},
  client: SupabaseClient = getAdminClient(),
): Promise<number> {
  const episodeNumber = opts.episodeNumber ?? 1;
  const { data, error } = await client
    .from('episodes')
    .upsert(
      {
        work_id: workId,
        episode_number: episodeNumber,
        title: opts.title ?? `E2E 회차 ${episodeNumber}`,
        content: opts.content ?? DEFAULT_EPISODE_CONTENT,
      },
      { onConflict: 'work_id,episode_number' },
    )
    .select('id')
    .single();
  if (error) throw new Error(`seedEpisode upsert failed: ${error.message}`);
  return Number(data.id);
}

/**
 * Always inserts a new analysis_runs row (no business UNIQUE). Caller manages cleanup.
 */
export async function seedAnalysisRun(
  episodeId: number,
  workId: number,
  mockResult?: MockSixAxisScores | Record<string, unknown>,
  client: SupabaseClient = getAdminClient(),
): Promise<number> {
  const result_json =
    mockResult && typeof mockResult === 'object' && 'dimensions' in mockResult
      ? mockResult
      : DEFAULT_MOCK_RESULT(mockResult as MockSixAxisScores | undefined);
  const { data, error } = await client
    .from('analysis_runs')
    .insert({
      episode_id: episodeId,
      work_id: workId,
      agent_version: 'e2e-mock-v1',
      result_json,
    })
    .select('id')
    .single();
  if (error) throw new Error(`seedAnalysisRun insert failed: ${error.message}`);
  return Number(data.id);
}

const STUDIO_BASELINE_TAG = 'studio-baseline';

type StudioBaselineWorkSpec = {
  title: string;
  genre: string;
  status: '연재중' | '휴재' | '완결';
  scores: number[]; // 회차당 overall_score (Sparkline + agentScore)
};

/**
 * Phase 2-D-7 /studio visual baseline용 작품 4건 idempotent seed.
 *
 * 작품 구성 (filter 분기 + GenreTag 색상 5종 + Sparkline 패턴 다양화):
 *   - 로맨스 / 연재중 / 5화 / rising trend (avg 84 → amber 80+)
 *   - 무협 / 연재중 / 6화 / high stable (avg 91 → emerald 90+)
 *   - 판타지 / 휴재 / 4화 / low (avg 66 → orange 60+)
 *   - 스포츠 / 완결 / 6화 / mid-high stable (avg 88 → amber 80+)
 *
 * 'studio-baseline' 태그로 격리 — 기존 seedEmptyWork ('e2e' 태그) 와 공존.
 * 동일 author + 동일 title 조합으로 idempotent (기존 행 발견 시 재사용, 회차/분석은 upsert).
 */
export async function seedStudioBaselineWorks(
  authUserId: string,
  client: SupabaseClient = getAdminClient(),
): Promise<number[]> {
  const specs: StudioBaselineWorkSpec[] = [
    {
      title: 'E2E baseline · 황실의 그림자',
      genre: '로맨스',
      status: '연재중',
      scores: [78, 82, 89, 84, 87],
    },
    {
      title: 'E2E baseline · 검신 무제',
      genre: '무협',
      status: '연재중',
      scores: [88, 90, 89, 92, 91, 93],
    },
    {
      title: 'E2E baseline · 마지막 마법사',
      genre: '판타지',
      status: '휴재',
      scores: [62, 68, 70, 65],
    },
    {
      title: 'E2E baseline · 구단주의 백서',
      genre: '스포츠',
      status: '완결',
      scores: [85, 88, 89, 87, 90, 88],
    },
  ];

  const userId = await resolvePublicUserIdByAuthId(client, authUserId);
  const workIds: number[] = [];

  for (const spec of specs) {
    // 1) work upsert by (author_id, title) — idempotent on rerun
    const { data: existing, error: lookupErr } = await client
      .from('works')
      .select('id')
      .eq('author_id', userId)
      .eq('title', spec.title)
      .is('deleted_at', null)
      .maybeSingle();
    if (lookupErr) throw new Error(`seedStudioBaselineWorks lookup failed: ${lookupErr.message}`);

    let workId: number;
    if (existing) {
      workId = Number(existing.id);
    } else {
      const { data: inserted, error: insErr } = await client
        .from('works')
        .insert({
          title: spec.title,
          genre: spec.genre,
          status: spec.status,
          author_id: userId,
          tags: [STUDIO_BASELINE_TAG],
        })
        .select('id')
        .single();
      if (insErr) throw new Error(`seedStudioBaselineWorks insert failed: ${insErr.message}`);
      workId = Number(inserted.id);
    }
    workIds.push(workId);

    // 2) 회차별 episode + analysis_run upsert
    //    seedEpisode는 (work_id, episode_number) UNIQUE로 idempotent.
    //    seedAnalysisRun은 매번 INSERT → 중복 방지 위해 사전 조회 후 skip.
    for (let i = 0; i < spec.scores.length; i++) {
      const episodeNumber = i + 1;
      const episodeId = await seedEpisode(
        workId,
        {
          episodeNumber,
          title: `${spec.title} ${episodeNumber}화`,
        },
        client,
      );

      const { data: existingRun } = await client
        .from('analysis_runs')
        .select('id')
        .eq('episode_id', episodeId)
        .eq('work_id', workId)
        .eq('agent_version', 'e2e-mock-v1')
        .limit(1)
        .maybeSingle();
      if (existingRun) continue;

      await seedAnalysisRun(
        episodeId,
        workId,
        {
          hook: spec.scores[i],
          character: spec.scores[i],
          world: spec.scores[i],
          tension: spec.scores[i],
          emotion: spec.scores[i],
          originality: spec.scores[i],
        },
        client,
      );
    }
  }

  return workIds;
}

/**
 * Always inserts a new analysis_jobs row.
 * appUserId is public.users.id (bigint), NOT auth.users.id.
 * status must be one of: 'pending' | 'processing' | 'completed' | 'failed'
 * (analysis_jobs_status_check). Default 'completed' marks the job done with a run linked.
 */
export async function seedAnalysisJob(
  appUserId: number,
  episodeId: number,
  runId: number,
  status: 'pending' | 'processing' | 'completed' | 'failed' = 'completed',
  client: SupabaseClient = getAdminClient(),
): Promise<string> {
  const { data, error } = await client
    .from('analysis_jobs')
    .insert({
      app_user_id: appUserId,
      episode_id: episodeId,
      analysis_run_id: runId,
      status,
    })
    .select('id')
    .single();
  if (error) throw new Error(`seedAnalysisJob insert failed: ${error.message}`);
  return String(data.id);
}
